spring:
  datasource:
    username: root
    password: student
    url: jdbc:mysql://localhost:3306/blog8?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    check-template-location: false
    enable-spring-el-compiler: true
server:
  port: 8188

mybatis:
  config-location: classpath:/mybatis/mybatis.xml

blog:
  file:
    enabled: true
    upload-path: /Users/liqiwen/upload
    upload-thumb-path: /Users/liqiwen/upload/thumb
    total-Sem: 5
    ffmpeg-path: /Users/liqiwen/develop/ffmpeg-20200831-4a11a6f-macos64-static/bin/ffmpeg
    graphics-magick-path: /usr/local/GraphicsMagick-1.3.28/bin/gm
  core:
    default-page-size: 10
    markdown-server-url: http://127.0.0.1:3000
    ip-header: X-Token
    token-header: x-auth-token
    url-prefix: http://localhost:8188/
    max-article-tag-size: 5
    backup: true
    cors-enabled: true
